name: my_firebase_storage
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.10
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  provider: ^6.0.2
  fluttertoast: ^8.0.9
  get: ^4.6.1
  shared_preferences: ^2.0.13
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  firebase_storage: ^10.2.13
  cloud_firestore: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
     - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
